
import { Fighter, Player } from "discordjs-rpg";
import { code, random } from "../utils";

export class Monster extends Fighter {
  readonly DIFF = 2;
  drop = random().integer(150, 500);
  xpDrop = random().integer(10, 35);
  
  constructor(player: Player) {
    super(random().pick(names));
    this.attack = player.attack + random().integer(-2, 5);
    this.hp = player.hp + random().integer(-3, 6);
    this.armor = player.armor + (random().integer(-1, 4) / 100);
    this.critChance = player.critChance + (random().integer(-2, 5) / 100);
    this.critDamage = player.critDamage + random().integer(0.1, 0.5);
  }

  show() {
    const profile = super.show();

    profile.addField("Armoran Shard Drop", code(this.drop), true);
    profile.addField("xp Drop", code(this.xpDrop), true);

    return profile;
  }
}


const names = [
  "Aboleth",
  "Acolyte",
  "Adult Black Dragon",
  "Adult Blue Dragon",
  "Adult Brass Dragon",
  "Adult Bronze Dragon",
  "Adult Copper Dragon",
  "Adult Gold Dragon",
  "Adult Green Dragon",
  "Adult Red Dragon",
  "Adult Silver Dragon",
  "Adult White Dragon",
  "Air Elemental",
  "Allosaurus",
  "Ancient Black Dragon",
  "Ancient Blue Dragon",
  "Ancient Brass Dragon",
  "Ancient Bronze Dragon",
  "Ancient Copper Dragon",
  "Ancient Gold Dragon",
  "Ancient Green Dragon",
  "Ancient Red Dragon",
  "Ancient Silver Dragon",
  "Ancient White Dragon",
  "Androsphinx",
  "Animated Armor",
  "Ankheg",
  "Ankylosaurus",
  "Ape",
  "Archmage",
  "Assassin",
  "Awakened Shrub",
  "Awakened Tree",
  "Axe Beak",
  "Azer",
  "Baboon",
  "Badger",
  "Balor",
  "Bandit",
  "Bandit Captain",
  "Banshee",
  "Barbed Devil",
  "Basilisk",
  "Bat",
  "Bearded Devil",
  "Behir",
  "Berserker",
  "Black Bear",
  "Black Dragon Wyrmling",
  "Black Pudding",
  "Blink Dog",
  "Blood Hawk",
  "Blue Dragon Wyrmling",
  "Boar",
  "Bone Devil",
  "Brass Dragon Wyrmling",
  "Bronze Dragon Wyrmling",
  "Brown Bear",
  "Bugbear",
  "Bulette",
  "Camel",
  "Cat",
  "Centaur",
  "Chain Devil",
  "Chimera",
  "Chuul",
  "Clay Golem",
  "Cloaker",
  "Cloud Giant",
  "Cockatrice",
  "Commoner",
  "Constrictor Snake",
  "Copper Dragon Wyrmling",
  "Couatl",
  "Crab",
  "Crocodile",
  "Cult Fanatic",
  "Cultist",
  "Cyclops",
  "Darkmantle",
  "Death Dog",
  "Deep Gnome (Svirfneblin)",
  "Deer",
  "Deva",
  "Dire Wolf",
  "Djinni",
  "Doppelganger",
  "Draft Horse",
  "Dragon Turtle",
  "Dretch",
  "Drider",
  "Drow",
  "Druid",
  "Dryad",
  "Duergar",
  "Dust Mephit",
  "Eagle",
  "Earth Elemental",
  "Efreeti",
  "Elephant",
  "Elk",
  "Erinyes",
  "Ettercap",
  "Ettin",
  "Fire Elemental",
  "Fire Giant",
  "Flameskull",
  "Flesh Golem",
  "Flying Snake",
  "Flying Sword",
  "Frog",
  "Frost Giant",
  "Gargoyle",
  "Gelatinous Cube",
  "Ghast",
  "Ghost",
  "Ghoul",
  "Giant Ape",
  "Giant Badger",
  "Giant Bat",
  "Giant Boar",
  "Giant Centipede",
  "Giant Constrictor Snake",
  "Giant Crab",
  "Giant Crocodile",
  "Giant Eagle",
  "Giant Elk",
  "Giant Fire Beetle",
  "Giant Frog",
  "Giant Goat",
  "Giant Hyena",
  "Giant Lizard",
  "Giant Octopus",
  "Giant Owl",
  "Giant Poisonous Snake",
  "Giant Rat",
  "Giant Scorpion",
  "Giant Sea Horse",
  "Giant Shark",
  "Giant Spider",
  "Giant Toad",
  "Giant Vulture",
  "Giant Wasp",
  "Giant Weasel",
  "Giant Wolf Spider",
  "Gibbering Mouther",
  "Glabrezu",
  "Gladiator",
  "Gnoll",
  "Goat",
  "Goblin",
  "Gold Dragon Wyrmling",
  "Gorgon",
  "Gray Ooze",
  "Green Dragon Wyrmling",
  "Green Hag",
  "Grick",
  "Griffon",
  "Grimlock",
  "Guard",
  "Guardian Naga",
  "Gynosphinx",
  "Half-Red Dragon Veteran",
  "Harpy",
  "Hawk",
  "Hell Hound",
  "Hezrou",
  "Hill Giant",
  "Hippogriff",
  "Hobgoblin",
  "Homunculus",
  "Horned Devil",
  "Hunter Shark",
  "Hydra",
  "Hyena",
  "Ice Devil",
  "Ice Mephit",
  "Imp",
  "Invisible Stalker",
  "Iron Golem",
  "Jackal",
  "Killer Whale",
  "Knight",
  "Kobold",
  "Kraken",
  "Lamia",
  "Lemure",
  "Lich",
  "Lion",
  "Lizard",
  "Lizardfolk",
  "Mage",
  "Magma Mephit",
  "Magmin",
  "Mammoth",
  "Manticore",
  "Marilith",
  "Mastiff",
  "Medusa",
  "Merfolk",
  "Merrow",
  "Mimic",
  "Minotaur",
  "Minotaur Skeleton",
  "Mule",
  "Mummy",
  "Mummy Lord",
  "Nalfeshnee",
  "Night Hag",
  "Nightmare",
  "Noble",
  "Nothic",
  "Ochre Jelly",
  "Octopus",
  "Ogre",
  "Ogre Zombie",
  "Oni",
  "Orc",
  "Otyugh",
  "Owl",
  "Owlbear",
  "Panther",
  "Pegasus",
  "Phase Spider",
  "Pit Fiend",
  "Planetar",
  "Plesiosaurus",
  "Poisonous Snake",
  "Polar Bear",
  "Pony",
  "Priest",
  "Pseudodragon",
  "Pteranodon",
  "Purple Worm",
  "Quasit",
  "Quipper",
  "Rakshasa",
  "Rat",
  "Raven",
  "Red Dragon Wyrmling",
  "Reef Shark",
  "Remorhaz",
  "Rhinoceros",
  "Riding Horse",
  "Roc",
  "Roper",
  "Rug of Smothering",
  "Rust Monster",
  "Saber-Toothed Tiger",
  "Sahuagin",
  "Salamander",
  "Satyr",
  "Scorpion",
  "Scout",
  "Sea Hag",
  "Sea Horse",
  "Shadow",
  "Shambling Mound",
  "Shield Guardian",
  "Shrieker",
  "Silver Dragon Wyrmling",
  "Skeleton",
  "Solar",
  "Spectator",
  "Specter",
  "Spider",
  "Spirit Naga",
  "Sprite",
  "Spy",
  "Steam Mephit",
  "Stirge",
  "Stone Giant",
  "Stone Golem",
  "Storm Giant",
  "Succubus/Incubus",
  "Swarm of Bats",
  "Swarm of Insects",
  "Swarm of Poisonous Snakes",
  "Swarm of Quippers",
  "Swarm of Rats",
  "Swarm of Ravens",
  "Tarrasque",
  "Thug",
  "Tiger",
  "Treant",
  "Tribal Warrior",
  "Triceratops",
  "Troll",
  "Twig Blight",
  "Tyrannosaurus Rex",
  "Unicorn",
  "Vampire",
  "Vampire Spawn",
  "Veteran",
  "Violet Fungus",
  "Vrock",
  "Vulture",
  "Warhorse",
  "Warhorse Skeleton",
  "Water Elemental",
  "Weasel",
  "Werebear",
  "Wereboar",
  "Wererat",
  "Weretiger",
  "Werewolf",
  "White Dragon Wyrmling",
  "Wight",
  "Will-o'-Wisp",
  "Winter Wolf",
  "Wolf",
  "Worg",
  "Wraith",
  "Wyvern",
  "Xorn",
  "Yeti",
  "Young Black Dragon",
  "Young Blue Dragon",
  "Young Brass Dragon",
  "Young Bronze Dragon",
  "Young Copper Dragon",
  "Young Gold Dragon",
  "Young Green Dragon",
  "Young Red Dragon",
  "Young Silver Dragon",
  "Young White Dragon",
  "Zombie"
]
