
function combinator(a: string[], b: { name: string, url: string }[]) {
  const result: { name: string, url: string }[] = [];

  for (const j of b) {
    for (const i of a) {
      result.push({ name: `${i} ${j.name}`, url: j.url })
    }
  }

  return result;
}

const levels = [
  "Weak",
  "Strong",
  "Super",
];

const names = [
  {"name":"'Rum'-pumped crab","url":"https://www.runehq.com/image/monsterdb/r/rumpumpedcrab.png"},
  {"name":"Abomination","url":"https://www.runehq.com/image/monsterdb/a/abomination.png"},
  {"name":"Abyssal leech","url":"https://www.runehq.com/image/monsterdb/a/abyssalleech.png"},
  {"name":"Acheron mammoth","url":"https://www.runehq.com/image/monsterdb/a/acheronmammoth.png"},
  {"name":"Adolescent White wolf","url":"https://www.runehq.com/image/monsterdb/a/adolescentwhitewolf.png"},
  {"name":"Air Elemental","url":"https://www.runehq.com/image/monsterdb/a/airelemental.png"},
  {"name":"Airut","url":"https://www.runehq.com/image/monsterdb/a/airut.png"},
  {"name":"Al-Kharid warrior","url":"https://www.runehq.com/image/monsterdb/a/alkharidwarrior.png"},
  {"name":"Albino bat","url":"https://www.runehq.com/image/monsterdb/a/albinobat.png"},
  {"name":"Alomone","url":"https://www.runehq.com/image/monsterdb/a/alomone.png"},
  {"name":"Ambassador Jabari","url":"https://www.runehq.com/image/monsterdb/a/ambassadorjabari.png"},
  {"name":"Anagami","url":"https://www.runehq.com/image/monsterdb/a/anagami.png"},
  {"name":"Ancestral orokami","url":"https://www.runehq.com/image/monsterdb/a/ancestralorokami.png"},
  {"name":"Animated spade","url":"https://www.runehq.com/image/monsterdb/a/animatedspade.png"},
  {"name":"Anja","url":"https://www.runehq.com/image/monsterdb/a/anja.png"},
  {"name":"Aquatic jadinko","url":"https://www.runehq.com/image/monsterdb/a/aquaticjadinko.png"},
  {"name":"Araxxor","url":"https://www.runehq.com/image/monsterdb/a/araxxor.png"},
  {"name":"Archer","url":"https://www.runehq.com/image/monsterdb/a/archer.png"},
  {"name":"Armoured zombie","url":"https://www.runehq.com/image/monsterdb/a/armouredzombie.png"},
  {"name":"Arrg","url":"https://www.runehq.com/image/monsterdb/a/arrg.png"},
  {"name":"Automaton","url":"https://www.runehq.com/image/monsterdb/a/automaton.png"},
  {"name":"Automaton Generator","url":"https://www.runehq.com/image/monsterdb/a/automatongenerator.png"},
  {"name":"Baby roc","url":"https://www.runehq.com/image/monsterdb/b/babyroc.png"},
  {"name":"Baby blue dragon","url":"https://www.runehq.com/image/monsterdb/b/babybluedragon.png"},
  {"name":"Bandit looter","url":"https://www.runehq.com/image/monsterdb/b/banditlooter.png"},
  {"name":"Avatar of Creation","url":"https://www.runehq.com/image/monsterdb/a/avatarofcreation.png"},
  {"name":"Automaton Tracer","url":"https://www.runehq.com/image/monsterdb/a/automatontracer.png"},
  {"name":"Banshee","url":"https://www.runehq.com/image/monsterdb/b/banshee.png"},
  {"name":"Bagrada rex","url":"https://www.runehq.com/image/monsterdb/b/bagradarex.png"},
  {"name":"Billy Goat","url":"https://www.runehq.com/image/monsterdb/b/billygoat.png"},
  {"name":"Big Wolf","url":"https://www.runehq.com/image/monsterdb/b/bigwolf.png"},
  {"name":"Beastmaster Durzag","url":"https://www.runehq.com/image/monsterdb/b/beastmasterdurzag.png"},
  {"name":"Black unicorn","url":"https://www.runehq.com/image/monsterdb/b/blackunicorn.png"},
  {"name":"Blood reaver","url":"https://www.runehq.com/image/monsterdb/b/bloodreaver.png"},
  {"name":"Boris","url":"https://www.runehq.com/image/monsterdb/b/boris.png"},
  {"name":"Blue dragon","url":"https://www.runehq.com/image/monsterdb/b/bluedragon.png"},
  {"name":"Blood blamish snail","url":"https://www.runehq.com/image/monsterdb/b/bloodblamishsnail.png"},
  {"name":"Breoca","url":"https://www.runehq.com/image/monsterdb/b/breoca.png"},
  {"name":"Broddi","url":"https://www.runehq.com/image/monsterdb/b/broddi.png"},
  {"name":"Bruise blamish snail","url":"https://www.runehq.com/image/monsterdb/b/bruiseblamishsnail.png"},
  {"name":"Bundling orokami","url":"https://www.runehq.com/image/monsterdb/b/bundlingorokami.png"},
  {"name":"Bulwark beast","url":"https://www.runehq.com/image/monsterdb/b/bulwarkbeast.png"},
  {"name":"Brutish dinosaur","url":"https://www.runehq.com/image/monsterdb/b/brutishdinosaur.png"},
  {"name":"Bronze dragon","url":"https://www.runehq.com/image/monsterdb/b/bronzedragon.png"},
  {"name":"Borrokar","url":"https://www.runehq.com/image/monsterdb/b/borrokar.png"},
  {"name":"Camp dweller","url":"https://www.runehq.com/image/monsterdb/c/campdweller.png"},
  {"name":"Captured Meiyerditch citizen","url":"https://www.runehq.com/image/monsterdb/c/capturedmeiyerditchcitizen.png"},
  {"name":"Camel warrior","url":"https://www.runehq.com/image/monsterdb/c/camelwarrior.png"},
  {"name":"Chaos giant","url":"https://www.runehq.com/image/monsterdb/c/chaosgiant.png"},
  {"name":"Chinchompa","url":"https://www.runehq.com/image/monsterdb/c/chinchompa.png"},
  {"name":"Chaos dwogre","url":"https://www.runehq.com/image/monsterdb/c/chaosdwogre.png"},
  {"name":"Chronozon","url":"https://www.runehq.com/image/monsterdb/c/chronozon.png"},
  {"name":"Cockroach drone","url":"https://www.runehq.com/image/monsterdb/c/cockroachdrone.png"},
  {"name":"Clawdia","url":"https://www.runehq.com/image/monsterdb/c/clawdia.png"},
  {"name":"Clivet","url":"https://www.runehq.com/image/monsterdb/c/clivet.png"},
  {"name":"Cockroach worker","url":"https://www.runehq.com/image/monsterdb/c/cockroachworker.png"},
  {"name":"Dagannoth Rex","url":"https://www.runehq.com/image/monsterdb/d/dagannothrex.png"},
  {"name":"Dashing kebbit","url":"https://www.runehq.com/image/monsterdb/d/dashingkebbit.png"},
  {"name":"Dark energy core","url":"https://www.runehq.com/image/monsterdb/d/darkenergycore.png"},
  {"name":"Death spawn","url":"https://www.runehq.com/image/monsterdb/d/deathspawn.png"},
  {"name":"Deadly red spider","url":"https://www.runehq.com/image/monsterdb/d/deadlyredspider.png"},
  {"name":"Dark Lord","url":"https://www.runehq.com/image/monsterdb/d/darklord.png"},
  {"name":"Desert snake","url":"https://www.runehq.com/image/monsterdb/d/desertsnake.png"},
  {"name":"Dagannoth Supreme","url":"https://www.runehq.com/image/monsterdb/d/dagannothsupreme.png"},
  {"name":"Drake","url":"https://www.runehq.com/image/monsterdb/d/drake.png"},
  {"name":"Devil's snare","url":"https://www.runehq.com/image/monsterdb/d/devilssnare.png"},
  {"name":"Drunken man","url":"https://www.runehq.com/image/monsterdb/d/drunkenman.png"},
  {"name":"Dragith nurn","url":"https://www.runehq.com/image/monsterdb/d/dragithnurn.png"},
  {"name":"Eduard","url":"https://www.runehq.com/image/monsterdb/e/eduard.png"},
  {"name":"Double agent","url":"https://www.runehq.com/image/monsterdb/d/doubleagent.png"},
  {"name":"Dung kalphite","url":"https://www.runehq.com/image/monsterdb/d/dungkalphite.png"},
  {"name":"Diseased jadinko","url":"https://www.runehq.com/image/monsterdb/d/diseasedjadinko.png"},
  {"name":"Duckling","url":"https://www.runehq.com/image/monsterdb/d/duckling.png"},
  {"name":"Donny the Lad","url":"https://www.runehq.com/image/monsterdb/d/donnythelad.png"},
  {"name":"Elvarg","url":"https://www.runehq.com/image/monsterdb/e/elvarg.png"},
  {"name":"Exiled kalphite guardian","url":"https://www.runehq.com/image/monsterdb/e/exiledkalphiteguardian.png"},
  {"name":"Exiled kalphite soldier","url":"https://www.runehq.com/image/monsterdb/e/exiledkalphitesoldier.png"},
  {"name":"Elite Dark Warrior","url":"https://www.runehq.com/image/monsterdb/e/elitedarkwarrior.png"},
  {"name":"Einar","url":"https://www.runehq.com/image/monsterdb/e/einar.png"},
  {"name":"Exiled kalphite paragon","url":"https://www.runehq.com/image/monsterdb/e/exiledkalphiteparagon.png"},
  {"name":"Feral dinosaur","url":"https://www.runehq.com/image/monsterdb/f/feraldinosaur.png"},
  {"name":"Fire giant","url":"https://www.runehq.com/image/monsterdb/f/firegiant.png"},
  {"name":"Elite Dark Mage","url":"https://www.runehq.com/image/monsterdb/e/elitedarkmage.png"},
  {"name":"Feline akh","url":"https://www.runehq.com/image/monsterdb/f/felineakh.png"},
  {"name":"Fever spider","url":"https://www.runehq.com/image/monsterdb/f/feverspider.png"},
  {"name":"Fire wizard","url":"https://www.runehq.com/image/monsterdb/f/firewizard.png"},
  {"name":"Foraging bakami","url":"https://www.runehq.com/image/monsterdb/f/foragingbakami.png"},
  {"name":"Flockleader Geerin","url":"https://www.runehq.com/image/monsterdb/f/flockleadergeerin.png"},
  {"name":"Force muspah","url":"https://www.runehq.com/image/monsterdb/f/forcemuspah.png"},
  {"name":"Fungal rodent","url":"https://www.runehq.com/image/monsterdb/f/fungalrodent.png"},
  {"name":"Georgy","url":"https://www.runehq.com/image/monsterdb/g/georgy.png"},
  {"name":"Fortunate orokami","url":"https://www.runehq.com/image/monsterdb/f/fortunateorokami.png"},
  {"name":"Fumus","url":"https://www.runehq.com/image/monsterdb/f/fumus.png"},
  {"name":"Fortress Guard","url":"https://www.runehq.com/image/monsterdb/f/fortressguard.png"},
  {"name":"Ghoul","url":"https://www.runehq.com/image/monsterdb/g/ghoul.png"},
  {"name":"Ghost","url":"https://www.runehq.com/image/monsterdb/g/ghost.png"},
  {"name":"Ghast","url":"https://www.runehq.com/image/monsterdb/g/ghast.png"},
  {"name":"Giant frog","url":"https://www.runehq.com/image/monsterdb/g/giantfrog.png"},
  {"name":"Giant crypt rat","url":"https://www.runehq.com/image/monsterdb/g/giantcryptrat.png"},
  {"name":"Giant ant worker","url":"https://www.runehq.com/image/monsterdb/g/giantantworker.png"},
  {"name":"Giant Rock Crab","url":"https://www.runehq.com/image/monsterdb/g/giantrockcrab.png"},
  {"name":"Giant mole","url":"https://www.runehq.com/image/monsterdb/g/giantmole.png"},
  {"name":"Glacies","url":"https://www.runehq.com/image/monsterdb/g/glacies.png"},
  {"name":"Golden warbler","url":"https://www.runehq.com/image/monsterdb/g/goldenwarbler.png"},
  {"name":"Gnome guard","url":"https://www.runehq.com/image/monsterdb/g/gnomeguard.png"},
  {"name":"Goat","url":"https://www.runehq.com/image/monsterdb/g/goat.png"},
  {"name":"Goblin Raider","url":"https://www.runehq.com/image/monsterdb/g/goblinraider.png"},
  {"name":"Gnome child","url":"https://www.runehq.com/image/monsterdb/g/gnomechild.png"},
  {"name":"Gladius","url":"https://www.runehq.com/image/monsterdb/g/gladius.png"},
  {"name":"Gnome troop","url":"https://www.runehq.com/image/monsterdb/g/gnometroop.png"},
  {"name":"Grotworm","url":"https://www.runehq.com/image/monsterdb/g/grotworm.png"},
  {"name":"Greater reborn ranger","url":"https://www.runehq.com/image/monsterdb/g/greaterrebornranger.png"},
  {"name":"Greater shadow","url":"https://www.runehq.com/image/monsterdb/g/greatershadow.png"},
  {"name":"Gregorovic","url":"https://www.runehq.com/image/monsterdb/g/gregorovic.png"},
  {"name":"Grifolapine","url":"https://www.runehq.com/image/monsterdb/g/grifolapine.png"},
  {"name":"Gu ronin","url":"https://www.runehq.com/image/monsterdb/g/guronin.png"},
  {"name":"Gullible tourist","url":"https://www.runehq.com/image/monsterdb/g/gullibletourist.png"},
  {"name":"Helwyr","url":"https://www.runehq.com/image/monsterdb/h/helwyr.png"},
  {"name":"Holthion","url":"https://www.runehq.com/image/monsterdb/h/holthion.png"},
  {"name":"Guthix jadinko","url":"https://www.runehq.com/image/monsterdb/g/guthixjadinko.png"},
  {"name":"Head Mourner","url":"https://www.runehq.com/image/monsterdb/h/headmourner.png"},
  {"name":"Hell-Rat","url":"https://www.runehq.com/image/monsterdb/h/hellrat.png"},
  {"name":"Ice demon","url":"https://www.runehq.com/image/monsterdb/i/icedemon.png"},
  {"name":"Ice nihil","url":"https://www.runehq.com/image/monsterdb/i/icenihil.png"},
  {"name":"Ice spider","url":"https://www.runehq.com/image/monsterdb/i/icespider.png"},
  {"name":"Ice troll male","url":"https://www.runehq.com/image/monsterdb/i/icetrollmale.png"},
  {"name":"Ice warrior","url":"https://www.runehq.com/image/monsterdb/i/icewarrior.png"},
  {"name":"Icefiend","url":"https://www.runehq.com/image/monsterdb/i/icefiend.png"},
  {"name":"Hydrix dragon","url":"https://www.runehq.com/image/monsterdb/h/hydrixdragon.png"},
  {"name":"Igneous jadinko","url":"https://www.runehq.com/image/monsterdb/i/igneousjadinko.png"},
  {"name":"Ice troll grunt","url":"https://www.runehq.com/image/monsterdb/i/icetrollgrunt.png"},
  {"name":"Jailer","url":"https://www.runehq.com/image/monsterdb/j/jailer.png"},
  {"name":"Khazard Guard","url":"https://www.runehq.com/image/monsterdb/k/khazardguard.png"},
  {"name":"Imre","url":"https://www.runehq.com/image/monsterdb/i/imre.png"},
  {"name":"Ket-Zek","url":"https://www.runehq.com/image/monsterdb/k/ketzek.png"},
  {"name":"K'ril Tsutsaroth","url":"https://www.runehq.com/image/monsterdb/k/kriltsutsaroth.png"},
  {"name":"Iron dragon","url":"https://www.runehq.com/image/monsterdb/i/irondragon.png"},
  {"name":"Khazard trooper","url":"https://www.runehq.com/image/monsterdb/k/khazardtrooper.png"},
  {"name":"Kree'arra","url":"https://www.runehq.com/image/monsterdb/k/kreearra.png"},
  {"name":"Killerwatt","url":"https://www.runehq.com/image/monsterdb/k/killerwatt.png"},
  {"name":"Kraka","url":"https://www.runehq.com/image/monsterdb/k/kraka.png"},
  {"name":"Lampenflora","url":"https://www.runehq.com/image/monsterdb/l/lampenflora.png"},
  {"name":"Leech","url":"https://www.runehq.com/image/monsterdb/l/leech.png"},
  {"name":"Kurask minion","url":"https://www.runehq.com/image/monsterdb/k/kuraskminion.png"},
  {"name":"Ksenia","url":"https://www.runehq.com/image/monsterdb/k/ksenia.png"},
  {"name":"Living rock striker","url":"https://www.runehq.com/image/monsterdb/l/livingrockstriker.png"},
  {"name":"Leprechaun Champion","url":"https://www.runehq.com/image/monsterdb/l/leprechaunchampion.png"},
  {"name":"Knight of Saradomin","url":"https://www.runehq.com/image/monsterdb/k/knightofsaradomin.png"},
  {"name":"Legio Quartus","url":"https://www.runehq.com/image/monsterdb/l/legioquartus.png"},
  {"name":"Legio Secundus","url":"https://www.runehq.com/image/monsterdb/l/legiosecundus.png"},
  {"name":"Living rock patriarch","url":"https://www.runehq.com/image/monsterdb/l/livingrockpatriarch.png"},
  {"name":"Loar shade","url":"https://www.runehq.com/image/monsterdb/l/loarshade.png"},
  {"name":"Mummy","url":"https://www.runehq.com/image/monsterdb/m/mummy.png"},
  {"name":"Monkey","url":"https://www.runehq.com/image/monsterdb/m/monkey.png"},
  {"name":"Mosschin","url":"https://www.runehq.com/image/monsterdb/m/mosschin.png"},
  {"name":"Mouse","url":"https://www.runehq.com/image/monsterdb/m/mouse.png"},
  {"name":"Mutated jadinko male","url":"https://www.runehq.com/image/monsterdb/m/mutatedjadinkomale.png"},
  {"name":"Ocga","url":"https://www.runehq.com/image/monsterdb/o/ocga.png"},
  {"name":"Nikolai","url":"https://www.runehq.com/image/monsterdb/n/nikolai.png"},
  {"name":"Oculi apoterrasaur","url":"https://www.runehq.com/image/monsterdb/o/oculiapoterrasaur.png"},
  {"name":"Mutated jadinko baby","url":"https://www.runehq.com/image/monsterdb/m/mutatedjadinkobaby.png"},
  {"name":"Nezikchened","url":"https://www.runehq.com/image/monsterdb/n/nezikchened.png"},
  {"name":"Ogre statue","url":"https://www.runehq.com/image/monsterdb/o/ogrestatue.png"},
  {"name":"Murderous orokami","url":"https://www.runehq.com/image/monsterdb/m/murderousorokami.png"},
  {"name":"Nightmare","url":"https://www.runehq.com/image/monsterdb/n/nightmare.png"},
  {"name":"Nex","url":"https://www.runehq.com/image/monsterdb/n/nex.png"},
  {"name":"Oipuis","url":"https://www.runehq.com/image/monsterdb/o/oipuis.png"},
  {"name":"Oily bakami","url":"https://www.runehq.com/image/monsterdb/o/oilybakami.png"},
  {"name":"Oomlie Bird","url":"https://www.runehq.com/image/monsterdb/o/oomliebird.png"},
  {"name":"Ork","url":"https://www.runehq.com/image/monsterdb/o/ork.png"},
  {"name":"Othainian","url":"https://www.runehq.com/image/monsterdb/o/othainian.png"},
  {"name":"Ouhai","url":"https://www.runehq.com/image/monsterdb/o/ouhai.png"},
  {"name":"Outlaw","url":"https://www.runehq.com/image/monsterdb/o/outlaw.png"},
  {"name":"Ork statue","url":"https://www.runehq.com/image/monsterdb/o/orkstatue.png"},
  {"name":"Pawya","url":"https://www.runehq.com/image/monsterdb/p/pawya.png"},
  {"name":"Penguin","url":"https://www.runehq.com/image/monsterdb/p/penguin.png"},
  {"name":"Paladin","url":"https://www.runehq.com/image/monsterdb/p/paladin.png"},
  {"name":"Queen spawn","url":"https://www.runehq.com/image/monsterdb/q/queenspawn.png"},
  {"name":"Pest Queen","url":"https://www.runehq.com/image/monsterdb/p/pestqueen.png"},
  {"name":"Pheasant","url":"https://www.runehq.com/image/monsterdb/p/pheasant.png"},
  {"name":"Ragnar","url":"https://www.runehq.com/image/monsterdb/r/ragnar.png"},
  {"name":"Revenant dark beast","url":"https://www.runehq.com/image/monsterdb/r/revenantdarkbeast.png"},
  {"name":"Rat","url":"https://www.runehq.com/image/monsterdb/r/rat.png"},
  {"name":"Ranalph Devere","url":"https://www.runehq.com/image/monsterdb/r/ranalphdevere.png"},
  {"name":"Revenant imp","url":"https://www.runehq.com/image/monsterdb/r/revenantimp.png"},
  {"name":"Revenant ork","url":"https://www.runehq.com/image/monsterdb/r/revenantork.png"},
  {"name":"Revenant dragon","url":"https://www.runehq.com/image/monsterdb/r/revenantdragon.png"},
  {"name":"Revenant hobgoblin","url":"https://www.runehq.com/image/monsterdb/r/revenanthobgoblin.png"},
  {"name":"Red dragon","url":"https://www.runehq.com/image/monsterdb/r/reddragon.png"},
  {"name":"Rogue","url":"https://www.runehq.com/image/monsterdb/r/rogue.png"},
  {"name":"Revenant vampyre","url":"https://www.runehq.com/image/monsterdb/r/revenantvampyre.png"},
  {"name":"Ripper demon","url":"https://www.runehq.com/image/monsterdb/r/ripperdemon.png"},
  {"name":"Rooster","url":"https://www.runehq.com/image/monsterdb/r/rooster.png"},
  {"name":"Rock lobster","url":"https://www.runehq.com/image/monsterdb/r/rocklobster.png"},
  {"name":"Scarab mage","url":"https://www.runehq.com/image/monsterdb/s/scarabmage.png"},
  {"name":"Riyl shadow","url":"https://www.runehq.com/image/monsterdb/r/riylshadow.png"},
  {"name":"Saradomin priest","url":"https://www.runehq.com/image/monsterdb/s/saradominpriest.png"},
  {"name":"Salty Crablet","url":"https://www.runehq.com/image/monsterdb/s/saltycrablet.png"},
  {"name":"Rock crab","url":"https://www.runehq.com/image/monsterdb/r/rockcrab.png"},
  {"name":"River Troll","url":"https://www.runehq.com/image/monsterdb/r/rivertroll.png"},
  {"name":"Rowdy Slave","url":"https://www.runehq.com/image/monsterdb/r/rowdyslave.png"},
  {"name":"Sakadagami","url":"https://www.runehq.com/image/monsterdb/s/sakadagami.png"},
  {"name":"Sabre-toothed kebbit","url":"https://www.runehq.com/image/monsterdb/s/sabretoothedkebbit.png"},
  {"name":"Rune dragon","url":"https://www.runehq.com/image/monsterdb/r/runedragon.png"},
  {"name":"Scabaras ranger","url":"https://www.runehq.com/image/monsterdb/s/scabarasranger.png"},
  {"name":"Salawa akh","url":"https://www.runehq.com/image/monsterdb/s/salawaakh.png"},
  {"name":"Seagull","url":"https://www.runehq.com/image/monsterdb/s/seagull.png"},
  {"name":"Sea Snake Young","url":"https://www.runehq.com/image/monsterdb/s/seasnakeyoung.png"},
  {"name":"Shadow demon","url":"https://www.runehq.com/image/monsterdb/s/shadowdemon.png"},
  {"name":"Seeker","url":"https://www.runehq.com/image/monsterdb/s/seeker.png"},
  {"name":"Sergeant Strongstack","url":"https://www.runehq.com/image/monsterdb/s/sergeantstrongstack.png"},
  {"name":"Shadow","url":"https://www.runehq.com/image/monsterdb/s/shadow.png"},
  {"name":"Seren mage","url":"https://www.runehq.com/image/monsterdb/s/serenmage.png"},
  {"name":"Shadow Warrior","url":"https://www.runehq.com/image/monsterdb/s/shadowwarrior.png"},
  {"name":"Shadow nihil","url":"https://www.runehq.com/image/monsterdb/s/shadownihil.png"},
  {"name":"Sergeant Grimspike","url":"https://www.runehq.com/image/monsterdb/s/sergeantgrimspike.png"},
  {"name":"Shantay Guard","url":"https://www.runehq.com/image/monsterdb/s/shantayguard.png"},
  {"name":"Skogre","url":"https://www.runehq.com/image/monsterdb/s/skogre.png"},
  {"name":"Skeleton Mage","url":"https://www.runehq.com/image/monsterdb/s/skeletonmage.png"},
  {"name":"Skeleton warlord","url":"https://www.runehq.com/image/monsterdb/s/skeletonwarlord.png"},
  {"name":"Smoke nihil","url":"https://www.runehq.com/image/monsterdb/s/smokenihil.png"},
  {"name":"Skulls scout","url":"https://www.runehq.com/image/monsterdb/s/skullsscout.png"},
  {"name":"Solus Dellagar","url":"https://www.runehq.com/image/monsterdb/s/solusdellagar.png"},
  {"name":"Slash Bash","url":"https://www.runehq.com/image/monsterdb/s/slashbash.png"},
  {"name":"Sotapanna","url":"https://www.runehq.com/image/monsterdb/s/sotapanna.png"},
  {"name":"Sofiya","url":"https://www.runehq.com/image/monsterdb/s/sofiya.png"},
  {"name":"Small scarab","url":"https://www.runehq.com/image/monsterdb/s/smallscarab.png"},
  {"name":"Speedy Keith","url":"https://www.runehq.com/image/monsterdb/s/speedykeith.png"},
  {"name":"Spectral attendant","url":"https://www.runehq.com/image/monsterdb/s/spectralattendant.png"},
  {"name":"Stalking bakami","url":"https://www.runehq.com/image/monsterdb/s/stalkingbakami.png"},
  {"name":"Spider","url":"https://www.runehq.com/image/monsterdb/s/spider.png"},
  {"name":"Spined Larupia","url":"https://www.runehq.com/image/monsterdb/s/spinedlarupia.png"},
  {"name":"Starlight","url":"https://www.runehq.com/image/monsterdb/s/starlight.png"},
  {"name":"Spellwisp","url":"https://www.runehq.com/image/monsterdb/s/spellwisp.png"},
  {"name":"Spring Elemental","url":"https://www.runehq.com/image/monsterdb/s/springelemental.png"},
  {"name":"Stick","url":"https://www.runehq.com/image/monsterdb/s/stick.png"},
  {"name":"Summer Elemental","url":"https://www.runehq.com/image/monsterdb/s/summerelemental.png"},
  {"name":"TokTz-Ket-Dill","url":"https://www.runehq.com/image/monsterdb/t/toktzketdill.png"},
  {"name":"The Sanctum Guardian","url":"https://www.runehq.com/image/monsterdb/t/thesanctumguardian.png"},
  {"name":"Thrower Troll","url":"https://www.runehq.com/image/monsterdb/t/throwertroll.png"},
  {"name":"Thug","url":"https://www.runehq.com/image/monsterdb/t/thug.png"},
  {"name":"TokHaar-Mej","url":"https://www.runehq.com/image/monsterdb/t/tokhaarmej.png"},
  {"name":"Thora","url":"https://www.runehq.com/image/monsterdb/t/thora.png"},
  {"name":"Suspicious outsider","url":"https://www.runehq.com/image/monsterdb/s/suspiciousoutsider.png"},
  {"name":"TokHaar-Hur","url":"https://www.runehq.com/image/monsterdb/t/tokhaarhur.png"},
  {"name":"TokHaar-Ket","url":"https://www.runehq.com/image/monsterdb/t/tokhaarket.png"},
  {"name":"TokHaar-Ket-Dill","url":"https://www.runehq.com/image/monsterdb/t/tokhaarketdill.png"},
  {"name":"TokHaar-Xil","url":"https://www.runehq.com/image/monsterdb/t/tokhaarxil.png"},
  {"name":"Troll brute","url":"https://www.runehq.com/image/monsterdb/t/trollbrute.png"},
  {"name":"Tower guard","url":"https://www.runehq.com/image/monsterdb/t/towerguard.png"},
  {"name":"Tortle","url":"https://www.runehq.com/image/monsterdb/t/tortle.png"},
  {"name":"Tree Spirit","url":"https://www.runehq.com/image/monsterdb/t/treespirit.png"},
  {"name":"TzHaar-Ket","url":"https://www.runehq.com/image/monsterdb/t/tzhaarket.png"},
  {"name":"Tyras guard","url":"https://www.runehq.com/image/monsterdb/t/tyrasguard.png"},
  {"name":"Tropical wagtail","url":"https://www.runehq.com/image/monsterdb/t/tropicalwagtail.png"},
  {"name":"Tstanon Karlak","url":"https://www.runehq.com/image/monsterdb/t/tstanonkarlak.png"},
  {"name":"TzHaar-Xil","url":"https://www.runehq.com/image/monsterdb/t/tzhaarxil.png"},
  {"name":"Tz-Kil","url":"https://www.runehq.com/image/monsterdb/t/tzkil.png"},
  {"name":"Ugthanki","url":"https://www.runehq.com/image/monsterdb/u/ugthanki.png"},
  {"name":"Umbra","url":"https://www.runehq.com/image/monsterdb/u/umbra.png"},
  {"name":"Undead Cow","url":"https://www.runehq.com/image/monsterdb/u/undeadcow.png"},
  {"name":"Ungadulu","url":"https://www.runehq.com/image/monsterdb/u/ungadulu.png"},
  {"name":"Unicorn foal","url":"https://www.runehq.com/image/monsterdb/u/unicornfoal.png"},
  {"name":"Uodai","url":"https://www.runehq.com/image/monsterdb/u/uodai.png"},
  {"name":"Unspeakable horror","url":"https://www.runehq.com/image/monsterdb/u/unspeakablehorror.png"},
  {"name":"Vampyre Juvenile","url":"https://www.runehq.com/image/monsterdb/v/vampyrejuvenile.png"},
  {"name":"Vindicta","url":"https://www.runehq.com/image/monsterdb/v/vindicta.png"},
  {"name":"Viyeldi","url":"https://www.runehq.com/image/monsterdb/v/viyeldi.png"},
  {"name":"Warped bat","url":"https://www.runehq.com/image/monsterdb/w/warpedbat.png"},
  {"name":"Vulture","url":"https://www.runehq.com/image/monsterdb/v/vulture.png"},
  {"name":"Warped fly","url":"https://www.runehq.com/image/monsterdb/w/warpedfly.png"},
  {"name":"Waterfiend","url":"https://www.runehq.com/image/monsterdb/w/waterfiend.png"},
  {"name":"Wall beast","url":"https://www.runehq.com/image/monsterdb/w/wallbeast.png"},
  {"name":"Vera","url":"https://www.runehq.com/image/monsterdb/v/vera.png"},
  {"name":"Vyrelord","url":"https://www.runehq.com/image/monsterdb/v/vyrelord.png"},
  {"name":"Wight","url":"https://www.runehq.com/image/monsterdb/w/wight.png"},
  {"name":"Weaponsmaster","url":"https://www.runehq.com/image/monsterdb/w/weaponsmaster.png"},
  {"name":"Wight footsoldier","url":"https://www.runehq.com/image/monsterdb/w/wightfootsoldier.png"},
  {"name":"Wormbrain","url":"https://www.runehq.com/image/monsterdb/w/wormbrain.png"},
  {"name":"Warped terrorbird","url":"https://www.runehq.com/image/monsterdb/w/warpedterrorbird.png"},
  {"name":"Witches experiment 2nd form","url":"https://www.runehq.com/image/monsterdb/w/witchesexperiment2ndform.png"},
  {"name":"Wild jade vine","url":"https://www.runehq.com/image/monsterdb/w/wildjadevine.png"},
  {"name":"Winter Elemental","url":"https://www.runehq.com/image/monsterdb/w/winterelemental.png"},
  {"name":"Water Elemental","url":"https://www.runehq.com/image/monsterdb/w/waterelemental.png"},
  {"name":"Yadviga","url":"https://www.runehq.com/image/monsterdb/y/yadviga.png"},
  {"name":"Yak","url":"https://www.runehq.com/image/monsterdb/y/yak.png"},
  {"name":"Young grotworm","url":"https://www.runehq.com/image/monsterdb/y/younggrotworm.png"},
  {"name":"Yellow salamander","url":"https://www.runehq.com/image/monsterdb/y/yellowsalamander.png"},
  {"name":"Zamorak Wizard","url":"https://www.runehq.com/image/monsterdb/z/zamorakwizard.png"},
  {"name":"Zogre","url":"https://www.runehq.com/image/monsterdb/z/zogre.png"},
  {"name":"Zombie swab","url":"https://www.runehq.com/image/monsterdb/z/zombieswab.png"},
  {"name":"Zamorak jadinko","url":"https://www.runehq.com/image/monsterdb/z/zamorakjadinko.png"},
  {"name":"Yt-MejKot","url":"https://www.runehq.com/image/monsterdb/y/ytmejkot.png"},
  {"name":"Zenevivia","url":"https://www.runehq.com/image/monsterdb/z/zenevivia.png"},
  {"name":"Zakl'n Gritch","url":"https://www.runehq.com/image/monsterdb/z/zaklngritch.png"},
];

export const monsterNames = combinator(levels, names);
